// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiCoreproject.Models;

#nullable disable

namespace WebApiCoreproject.Migrations
{
    [DbContext(typeof(EmpContext))]
    partial class EmpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApiCoreproject.Models.Employee", b =>
                {
                    b.Property<int>("Emp_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Emp_Id"), 1L, 1);

                    b.Property<string>("Emp_Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emp_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emp_FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Emp_dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emp_lastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Emp_Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Emp_Id = 1,
                            Emp_Contact = "745676574",
                            Emp_Email = "Jhon@gmail.com",
                            Emp_FirstName = "Jhon",
                            Emp_dob = new DateTime(2002, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Emp_lastName = "Son"
                        },
                        new
                        {
                            Emp_Id = 2,
                            Emp_Contact = "824534554",
                            Emp_Email = "sam@gmail.com",
                            Emp_FirstName = "sam",
                            Emp_dob = new DateTime(1999, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Emp_lastName = "T"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
